// <auto-generated />
namespace EquiposTecnicosSN.Web.DataContexts.EquiposMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOrdenDeTrabajo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOrdenDeTrabajo));
        
        string IMigrationMetadata.Id
        {
            get { return "201604130144279_AddOrdenDeTrabajo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
